//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDiemRenLuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangDiemRenLuyen()
        {
            this.ChiTietTieuChis = new HashSet<ChiTietTieuChi>();
        }
    
        public int MaBangDRL { get; set; }
        public Nullable<int> DiemToiDa { get; set; }
        public Nullable<int> DiemTong { get; set; }
        public Nullable<int> MaHK_NH { get; set; }
        public string MaSV { get; set; }
    
        public virtual HocKy_NamHoc HocKy_NamHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTieuChi> ChiTietTieuChis { get; set; }
    }
}
