//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTieuChi
    {
        public int MaBangDRL { get; set; }
        public int MaTieuChi { get; set; }
        public Nullable<int> Diem { get; set; }
    
        public virtual BangDiemRenLuyen BangDiemRenLuyen { get; set; }
        public virtual TieuChi TieuChi { get; set; }
    }
}
