//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public string MaVT { get; set; }
        public string MaCN { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
