//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.KetQuas = new HashSet<KetQua>();
        }
        [Required(ErrorMessage = "Nhập mã sinh viên")]
        public string MaSV { get; set; }
        [Required(ErrorMessage = "Nhập họ sinh viên")]
        public string HoSV { get; set; }
        [Required(ErrorMessage = "Nhập tên sinh viên")]
        public string TenSV { get; set; }
        
        public string GioiTinh { get; set; }
        [Required(ErrorMessage = "Nhập ngày sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        [Required(ErrorMessage = "Nhập số điện thoại")]
        public string SoDienThoai { get; set; }
        public string MaLop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
