//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVien
    {
        public string UserName { get; set; }
        public string HoTV { get; set; }
        public string TenTV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public Nullable<int> SoDienThoai { get; set; }
        public string MaVT { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
