//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien.Models
{
    using QuanLySinhVien.Models.Validation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThanhVien
    {
        [Display(Name = "Tên đăng nhập")]
        public string UserName { get; set; }
        [Display(Name = "Họ thành viên")]

        [NameValidation(ErrorMessage = "Họ thành viên không hợp lệ")]
        public string HoTV { get; set; }
        [Display(Name = "Tên thành viên")]

        [NameValidation(ErrorMessage = "Tên thành viên không hợp lệ")]
        public string TenTV { get; set; }
        [Display(Name = "Giới tính")]
        public string GioiTinh { get; set; }
        [Display(Name = "Ngày sinh")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Display(Name = "Quê quán")]
        public string QueQuan { get; set; }
        [Display(Name = "Số điện thoại")]
        public Nullable<int> SoDienThoai { get; set; }
        [Display(Name = "Vai trò")]
        public string MaVT { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
